GLOBAL.STRINGS.RECIPE_DESC.OPALAMULET = "源源不断的力量向我涌来."

GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.OPALAMULET =
{
    GENERIC = "我认为在某个时刻...它会自动启动.",
    CHARGING = "很有趣,月光是它的燃料.",
}

GLOBAL.STRINGS.CHARACTERS.WILLOW.DESCRIBE.OPALAMULET =
{
    GENERIC = "至少它不冷.",
    CHARGING = "它好像快要爆炸了!...也许不会?",
}

GLOBAL.STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.OPALAMULET =
{
    GENERIC = "强大的月力!",
    CHARGING = "它在吞噬月光?",
}

GLOBAL.STRINGS.CHARACTERS.WENDY.DESCRIBE.OPALAMULET =
{
    GENERIC = "这是一个被锁住的诅咒.",
    CHARGING = "它又充满了活力.",
}

GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE.OPALAMULET =
{
    GENERIC = "它需要用明亮的月光来充电",
    CHARGING = "先进的月阳能系统",
}

GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.OPALAMULET =
{
    GENERIC = "我确信它会对月光做出反应,但它会做什么呢?",
    CHARGING = "一股从天而降的能量!",
}

GLOBAL.STRINGS.CHARACTERS.WOODIE.DESCRIBE.OPALAMULET =
{
    GENERIC = "我不确定这是个好主意...",
    CHARGING = "我不应该离远点.",
}

GLOBAL.STRINGS.CHARACTERS.WAXWELL.DESCRIBE.OPALAMULET =
{
    GENERIC = "现在,我的全部潜力...",
    CHARGING = "爽!充能!",
}

GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.OPALAMULET =
{
    GENERIC = "这是我的朋友!",
    CHARGING = "已经是白天了吗?",
}

GLOBAL.STRINGS.CHARACTERS.WEBBER.DESCRIBE.OPALAMULET =
{
    GENERIC = "月神就在我们身边.",
    CHARGING = "我怎么能睡在这么亮的月光下呢?",
}

GLOBAL.STRINGS.CHARACTERS.WINONA.DESCRIBE.OPALAMULET =
{
    GENERIC = "没有开关?我怎么触发它呢?",
    CHARGING = "它连接夜空!",
}
