STRINGS.RECIPE_DESC.KLAUS_SACK = "内含四次元空间"

STRINGS.NAMES.DEER_ANTLER1 = "鹿之匙"
STRINGS.RECIPE_DESC.DEER_ANTLER1 = "无眼鹿角的形状"

STRINGS.NAMES.ACHIVBOOK_BIRDS = "世界上的鸟"
STRINGS.RECIPE_DESC.ACHIVBOOK_BIRDS = "1000个物种的生活习性、栖息地。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ACHIVBOOK_BIRDS = "里面有我最喜欢的裂空座。"

STRINGS.NAMES.ACHIVBOOK_GARDENING = "应用园艺学"
STRINGS.RECIPE_DESC.ACHIVBOOK_GARDENING = "照料喂养植物。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ACHIVBOOK_GARDENING = "能够帮助植物的生长。"

STRINGS.NAMES.ACHIVBOOK_SLEEP = "睡前的故事"
STRINGS.RECIPE_DESC.ACHIVBOOK_SLEEP = "安慰的传说送你去梦境。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ACHIVBOOK_SLEEP = "书籍形式的暖牛奶。"

STRINGS.NAMES.ACHIVBOOK_BRIMSTONE = "快要结束了！"
STRINGS.RECIPE_DESC.ACHIVBOOK_BRIMSTONE = "这个世界将在大火和苦难中终结！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ACHIVBOOK_BRIMSTONE = "哪里会出问题呢"

STRINGS.NAMES.ACHIVBOOK_TENTACLES = "在触手上"
STRINGS.RECIPE_DESC.ACHIVBOOK_TENTACLES = "让我们了解一下我们地下的朋友！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ACHIVBOOK_TENTACLES = "很难放下它，这本轻小说真厉害。"

STRINGS.ALLACHIVCURRENCY={
[1] = "获得成就【",
[2] = "】",
[3] = "   ",
[4] = "获得 ",
[5] = " 成就点数",
[6] = "【",
[7] = "查看成就",
[8] = "交换奖励",
[9] = "已完成：",
[10] = "已获得：x",
[11] = "春(鹿角鹅)",
[12] = "夏(龙蝇)",
[13] = "秋(熊灌)",
[14] = "冬(独眼巨鹿)",
[15] = "设置",
[16] = "放大",
[17] = "缩小",
[18] = "重置奖励",
}

STRINGS.ALLACHIVNAME={
["intogame"] = "欢迎来到清酒服",
["firsteat"] = "我不会吃你们一口东西",
["supereat"] = "真香",
["danding"] = "宝宝不挑食",
["messiah"] = "救世主",
["walkalot"] = "狗仔队长",
["stopalot"] = "咸鱼",
["tooyoung"] = "你对力量一无所知",
["evil"] = "森林的妖精",
["snake"] = "蛇皮走位",

["deathalot"] = "超鬼",
["nosanity"] = "人工智障",
["sick"] = "丧心病狂",
["coldblood"] = "冷血动物",
["burn"] = "火的传承人",
["freeze"] = "冻住不洗澡",
["goodman"] = "你是个好人",
["brother"] = "你对我就像哥哥一样",
["fishmaster"] = "钓鱼达人",
["pickmaster"] = "拾荒者",
["chopmaster"] = "蓝翔挖掘兔",
["cookmaster"] = "法国大厨",
["buildmaster"] = "巧夺天工",
["longage"] = "光阴似箭",
["noob"] = "萌新",
["luck"] = "欧皇",
["black"] = "我有特别的风骚技巧",
["tank"] = "人形坦克",
["angry"] = "超凶",
["icebody"] = "冰霜体质",
["firebody"] = "熔岩体质",
["moistbody"] = "湿身诱惑",

--=====================================
["a_yingguai"] = "如影随形",
["a_worm"] = "邪恶的龙",
["a_monkey"] = "猴子请来的逗逼",
["a_buzzard"] = "小鸭子嘎嘎叫",
["a_lightninggoat"] = "咩咩咩",
["a_spiderqueen"] = "征服蜘蛛精",
["a_spider"] = "屠杀蜘蛛",
["a_spider_warrior"] = "误入盘丝洞 Ⅰ",
["a_spider_dropper"] = "误入盘丝洞 Ⅱ",
["a_spider_hider"] = "误入盘丝洞 Ⅲ",
["a_spider_spitter"] = "误入盘丝洞 Ⅳ",
["a_warg"] = "征服狗王",
["a_hound"] = "单身狗",
["a_firehound"] = "热情的单身狗",
["a_icehound"] = "冷酷的单身狗",
["a_koalefant_summer"] = "红色象征",
["a_koalefant_winter"] = "蓝色象征",
["a_catcoon"] = "浣熊这么可爱",
["a_bunnyman"] = "兔兔辣么可爱",
["a_leif"] = "征服森林守护者",
["a_slurtle"] = "蜗牛不是牛",
["a_tallbird"] = "大鸟杀小鸟",
["a_walrus"] = "海象爸爸",
["a_bat"] = "蝙蝠侠",
["a_butterfly"] = "小黄油游戏",
["a_killerbee"] = "捅了蜂窝",
["a_deer"] = "鹿含",
["a_mole"] = "石头哪去了",
["a_mosquito"] = "吸血鬼",
["a_penguin"] = "Q币已到账",
["a_merm"] = "'美'人鱼",
["a_frog"] = "青蛙王子",
["a_beefalo"] = "牛头辅助",
["a_perd"] = "大吉大利,今晚吃鸡",
["a_krampus"] = "欧皇还是非酋",
["a_robin_crow"] = "乌鸦坐飞机",
["a_robin_robin"] = "红毛鸟",
["a_robin_winter"] = "白毛鸟",
["a_robin_canary"] = "金丝雀",
["a_pigman"] = "屠夫",
["a_shadow_knight"] = "基佬 Ⅰ",
["a_shadow_bishop"] = "基佬 Ⅱ",
["a_shadow_rook"] = "佬 Ⅲ",
["a_moose"] = "湿润的春季",
["a_dragonfly"] = "炎热的夏季",
["a_bearger"] = "凉爽的秋季",
["a_deerclops"] = "寒冷的冬季",
["a_stalker_forest"] = "森林破坏王",
["a_stalker"] = "猎人还是猎物",
["a_stalker_atrium"] = "征服黑暗",
["a_klaus"] = "冬季礼物",
["a_antlion"] = "征服沙漠之王",
["a_minotaur"] = "没有买卖就没有杀害",
["a_beequeen"] = "女王陛下",
["a_toadstool"] = "小试身手",
["a_toadstool_dark"] = "展现真正的实力",


["all"] = "我毕业了",

["a_1"] = "隐藏任务---清酒吃货",
["a_2"] = "隐藏任务---苟活于世",
["a_3"] = "隐藏任务---生产机器",
["a_4"] = "隐藏任务---清酒战神 ",
["a_5"] = "隐藏任务---受到一万点伤害",

["a_6"] = "美味佳肴",
["a_7"] = "石头成精",
["a_8"] = "桦树小妖精",


["a_9"] = "哈奇也不放过",
["a_10"] = "小兔子乖乖",
["a_11"] = "孤魂野鬼",
["a_12"] = "食人花吃人吗",
["a_13"] = "夏天最爱",
["a_14"] = "",
["a_15"] = "",


["a_tallbirdegg"] = "掏蛋高手",
["a_frogglebunwich"] = "舌尖上的饥荒Ⅰ",
["a_baconeggs"] = "舌尖上的饥荒Ⅱ",
["a_bonestew"] = "舌尖上的饥荒Ⅲ",
["a_fishtacos"] = "舌尖上的饥荒Ⅳ",
["a_turkeydinner"] = "舌尖上的饥荒Ⅴ",
["a_fishsticks"] = "舌尖上的饥荒Ⅵ",
["a_meatballs"] = "舌尖上的饥荒Ⅶ",
["a_perogies"] = "舌尖上的饥荒Ⅷ",
["a_bisque"] = "舌尖上的饥荒Ⅸ",
["a_surfnturf"] = "舌尖上的饥荒Ⅹ",
["a_tigershark"] = "虎口脱险",
["a_twister"] = "深陷漩涡",
["a_snake"] = "蛇皮怪",
["a_snake_poison"] = "以毒攻毒",
["a_crocodog"] = "鳄狗入侵Ⅰ",
["a_poisoncrocodog"] = "鳄狗入侵Ⅱ",
["a_watercrocodog"] = "鳄狗入侵Ⅲ",
["a_coffee"] = "咖啡快递",
["a_a1"] = "",
["a_a2"] = "",
["a_a3"] = "",
["a_a4"] = "奖励一点",
["a_a5"] = "舌尖上的饥荒ⅩⅠ",
["a_a6"] = "机械生物Ⅰ",
["a_a7"] = "机械生物Ⅱ",
["a_a8"] = "机械生物Ⅲ",
["a_a9"] = "",
["a_a10"] = "",

--=====================================

}

STRINGS.ALLACHIVINFO={
["intogame"] = "成功进入清酒服",
["firsteat"] = "吃下第一个食物",
["supereat"] = "吃了"..allachiv_eventdata["supereat"].."个食物",
["danding"] = "吃下"..allachiv_eventdata["danding"].."个怪物千层饼",
["messiah"] = "救活别人"..allachiv_eventdata["messiah"].."次",
["walkalot"] = "走路超过"..(allachiv_eventdata["walkalot"]/60).."分钟",
["stopalot"] = "停止不动并活着"..(allachiv_eventdata["stopalot"]/60).."分钟",
["tooyoung"] = "死于石头",
["evil"] = "与"..allachiv_eventdata["evil"].."棵曼德拉草交朋友",
["snake"] = "击杀"..allachiv_eventdata["snake"].."只触手",
["deathalot"] = "死亡达"..allachiv_eventdata["deathalot"].."次",
["nosanity"] = "空脑残状态达"..allachiv_eventdata["nosanity"].."秒",
["sick"] = "打死格罗姆",
["coldblood"] = "打死切斯特",
["burn"] = "身上着火",
["freeze"] = "被冻住",
["goodman"] = "与猪人交朋友"..allachiv_eventdata["goodman"].."次",
["brother"] = "与兔人交朋友"..allachiv_eventdata["goodman"].."次",
["fishmaster"] = "成功钓鱼"..allachiv_eventdata["fishmaster"].."次",
["pickmaster"] = "采摘"..allachiv_eventdata["pickmaster"].."次",
["chopmaster"] = "砍倒树或挖树根"..allachiv_eventdata["chopmaster"].."次",
["cookmaster"] = "用锅煮了"..allachiv_eventdata["cookmaster"].."个食物",
["buildmaster"] = "制造超过"..allachiv_eventdata["buildmaster"].."次",
["longage"] = "存活超过"..allachiv_eventdata["longage"].."天",
["noob"] = "死于黑暗",
["luck"] = "击杀小偷掉落小偷包",
["black"] = "被雷劈死",
["tank"] = "受到伤害超过"..allachiv_eventdata["tank"],
["angry"] = "造成伤害超过"..allachiv_eventdata["angry"],
["icebody"] = "过冷状态达"..allachiv_eventdata["icebody"].."秒",
["firebody"] = "过热状态达"..allachiv_eventdata["firebody"].."秒",
["moistbody"] = "满潮湿达"..allachiv_eventdata["moistbody"].."秒",

["all"] = "解开了所有成就",
["intogameafterall"] = "成功进入二周目",
["blackspat"] = "单杀钢羊",
--=====================================
["a_yingguai"] = "击杀"..allachiv_eventdata["a_yingguai"].."只影怪",
["a_worm"] = "击杀"..allachiv_eventdata["a_worm"].."条地龙",
["a_monkey"] = "击杀"..allachiv_eventdata["a_monkey"].."只猴子",
["a_buzzard"] = "击杀"..allachiv_eventdata["a_buzzard"].."只小鸭子",
["a_lightninggoat"] = "击杀"..allachiv_eventdata["a_lightninggoat"].."只电羊",
["a_spiderqueen"] = "击杀"..allachiv_eventdata["a_spiderqueen"].."只蜘蛛女王",
["a_spider"] = "击杀"..allachiv_eventdata["a_spider"].."只蜘蛛",
["a_spider_warrior"] = "击杀"..allachiv_eventdata["a_spider_warrior"].."只黄色蜘蛛",
["a_spider_dropper"] = "击杀"..allachiv_eventdata["a_spider_dropper"].."白色蜘蛛",
["a_spider_hider"] = "击杀"..allachiv_eventdata["a_spider_hider"].."洞穴蜘蛛",
["a_spider_spitter"] = "击杀"..allachiv_eventdata["a_spider_spitter"].."喷射蜘蛛",
["a_warg"] = "击杀"..allachiv_eventdata["a_warg"].."只狗王",
["a_hound"] = "击杀"..allachiv_eventdata["a_hound"].."只普通猎狗",
["a_firehound"] = "击杀"..allachiv_eventdata["a_firehound"].."只红色猎狗",
["a_icehound"] = "击杀"..allachiv_eventdata["a_icehound"].."只蓝色猎狗",
["a_koalefant_summer"] = "击杀"..allachiv_eventdata["a_koalefant_summer"].."只红象",
["a_koalefant_winter"] = "击杀"..allachiv_eventdata["a_koalefant_winter"].."只蓝象",
["a_catcoon"] = "击杀"..allachiv_eventdata["a_catcoon"].."只浣熊",
["a_bunnyman"] = "击杀"..allachiv_eventdata["a_bunnyman"].."只兔人",
["a_leif"] = "击杀"..allachiv_eventdata["a_leif"].."只树精",
--["a_shadow"] = "击杀暗影三基佬",
["a_slurtle"] = "击杀"..allachiv_eventdata["a_slurtle"].."只蜗牛",
["a_tallbird"] = "击杀"..allachiv_eventdata["a_tallbird"].."只高脚鸟",
["a_walrus"] = "击杀"..allachiv_eventdata["a_walrus"].."只海象",
["a_bat"] = "击杀"..allachiv_eventdata["a_bat"].."只蝙蝠",
["a_butterfly"] = "击杀"..allachiv_eventdata["a_butterfly"].."只蝴蝶",
["a_killerbee"] = "击杀"..allachiv_eventdata["a_killerbee"].."只杀人蜂",
["a_deer"] = "击杀"..allachiv_eventdata["a_deer"].."只小鹿",
["a_mole"] = "击杀"..allachiv_eventdata["a_mole"].."只鼹鼠",
["a_mosquito"] = "击杀"..allachiv_eventdata["a_mosquito"].."只蚊子",
["a_penguin"] = "击杀"..allachiv_eventdata["a_penguin"].."只企鹅",
["a_merm"] = "击杀"..allachiv_eventdata["a_merm"].."只鱼人",
["a_frog"] = "击杀"..allachiv_eventdata["a_frog"].."只青蛙",
["a_beefalo"] = "击杀"..allachiv_eventdata["a_beefalo"].."头牛",
["a_perd"] = "击杀"..allachiv_eventdata["a_perd"].."只火鸡",
["a_krampus"] = "击杀"..allachiv_eventdata["a_krampus"].."只坎普斯",

["a_robin_crow"] = "击杀"..allachiv_eventdata["a_robin_crow"].."只乌鸦",
["a_robin_robin"] = "击杀"..allachiv_eventdata["a_robin_robin"].."只红雀",
["a_robin_winter"] = "击杀"..allachiv_eventdata["a_robin_winter"].."只雪雀",
["a_robin_canary"] = "击杀"..allachiv_eventdata["a_robin_canary"].."金丝雀",
["a_pigman"] = "击杀"..allachiv_eventdata["a_pigman"].."只猪人",


["a_shadow_knight"] = "击杀暗影骑士",
["a_shadow_bishop"] = "击杀暗影主教",
["a_shadow_rook"] = "击杀暗影战车",
["a_moose"] = "击杀鹿鹅",
["a_dragonfly"] = "击杀龙蝇",
["a_bearger"] = "击杀熊大",
["a_deerclops"] = "击杀巨鹿",
["a_stalker_forest"] = "击杀森林守护者",
["a_stalker"] = "击杀远古狩猎者",
["a_stalker_atrium"] = "击杀远古影织者",
["a_klaus"] = "击杀克劳斯",
["a_antlion"] = "击杀蚁狮",
["a_minotaur"] = "击杀犀牛",
["a_beequeen"] = "击杀蜜蜂女王",
["a_toadstool"] = "击杀毒蕈",
["a_toadstool_dark"] = "击杀暗黑毒蕈",
--=====================================

["a_1"] = "吃了"..allachiv_eventdata["a_1"].."个食物",
["a_2"] = "存活超过"..allachiv_eventdata["a_2"].."天",
["a_3"] = "制造超过"..allachiv_eventdata["a_3"].."次",
["a_4"] = "造成伤害超过"..allachiv_eventdata["a_4"],
["a_5"] = "受到伤害超过"..allachiv_eventdata["a_5"],

["a_6"] = "吃下"..allachiv_eventdata["a_6"].."个鳗鱼料理",
["a_7"] = "喂养"..allachiv_eventdata["a_7"].."只石虾",
["a_8"] = "击杀"..allachiv_eventdata["a_8"].."只坚果",

["a_9"] = "打死哈奇",
["a_10"] = "击杀"..allachiv_eventdata["a_10"].."只兔子",
["a_11"] = "击杀"..allachiv_eventdata["a_11"].."只幽灵",
["a_12"] = "打掉"..allachiv_eventdata["a_12"].."个食人花眼睛",

["a_13"] = "吃下"..allachiv_eventdata["a_13"].."个冰激淋",

["a_14"] = "",
["a_15"] = "",

["a_tallbirdegg"] = "吃掉"..allachiv_eventdata["a_tallbirdegg"].."个高脚鸟蛋",
["a_frogglebunwich"] = "吃掉"..allachiv_eventdata["a_frogglebunwich"].."个青蛙三明治",
["a_baconeggs"] = "吃掉"..allachiv_eventdata["a_baconeggs"].."个鸡蛋火腿",
["a_bonestew"] = "吃掉"..allachiv_eventdata["a_bonestew"].."个肉汤",
["a_fishtacos"] = "吃掉"..allachiv_eventdata["a_fishtacos"].."个鱼炸玉米饼",
["a_turkeydinner"] = "吃掉"..allachiv_eventdata["a_turkeydinner"].."个火鸡正餐",
["a_fishsticks"] = "吃掉"..allachiv_eventdata["a_fishsticks"].."个炸鱼条",
["a_meatballs"] = "吃掉"..allachiv_eventdata["a_meatballs"].."个肉丸",
["a_perogies"] = "吃掉"..allachiv_eventdata["a_perogies"].."个饺子",
["a_bisque"] = "吃掉"..allachiv_eventdata["a_bisque"].."个帽贝浓汤",
["a_surfnturf"] = "吃掉"..allachiv_eventdata["a_surfnturf"].."个海鲜大排档",
["a_tigershark"] = "击杀虎鲨",
["a_twister"] = "击杀豹卷风",
["a_snake"] = "击杀"..allachiv_eventdata["a_snake"].."条红蛇",
["a_snake_poison"] = "击杀"..allachiv_eventdata["a_snake_poison"].."条毒蛇",
["a_crocodog"] = "击杀"..allachiv_eventdata["a_crocodog"].."普通鳄狗",
["a_poisoncrocodog"] = "击杀"..allachiv_eventdata["a_poisoncrocodog"].."只毒鳄狗",
["a_watercrocodog"] = "击杀"..allachiv_eventdata["a_watercrocodog"].."只水鳄狗",
["a_coffee"] = "吃掉"..allachiv_eventdata["a_coffee"].."个咖啡",
["a_a1"] = "吃掉"..allachiv_eventdata["a_a1"].."个",
["a_a2"] = "吃掉"..allachiv_eventdata["a_a2"].."个",
["a_a3"] = "吃掉"..allachiv_eventdata["a_a3"].."个",
["a_a4"] = "等级提升",
["a_a5"] = "吃掉"..allachiv_eventdata["a_a5"].."个蜜汁火腿",
["a_a6"] = "击杀"..allachiv_eventdata["a_a6"].."个骑士",
["a_a7"] = "击杀"..allachiv_eventdata["a_a7"].."个主教",
["a_a8"] = "击杀"..allachiv_eventdata["a_a8"].."个战车",
["a_a9"] = "吃掉"..allachiv_eventdata["a_a9"].."个",
["a_a10"] ="吃掉"..allachiv_eventdata["a_a10"].."个" ,



}